### ISSUE TITLE
message and images in a single message

### ISSUE THREAD

**Issue by rosenrot00** [t0mer/wapi-custom-notifier#12]
Hi there,

I thought through doing this it should be possible to send the message, title and images in one message. However, it creates two messages from it.

Could you elaborate what I'm doing wrong?

```
service: notify.wapi_whatsapp_notifire
data:
  message: The garage door has been open for 10 minutes.
  title: Your Garage Door Friend
  target: xxxxxxxxxx@c.us #Can be contact or group chat id
  data:
    media_url: |
      https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=Example
      https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=Example
```
