### ISSUE TITLE
QUESTION - API_KEY/TOKEN

### ISSUE THREAD

**Issue by sibero80** [t0mer/wapi-custom-notifier#4]
Greetings from Colombia, thanks for this wonderful work, it is very useful!
Wanted to ask you abouyt the API_KEY/TOKEN, what is it for? how do I generate one?
I got a new SIM just to test this in my Home.

Thank you!

**Comment by ChrAnd2** [comment]
Hey @sibero80,

sorry for the late response. 
Can you give a bit more information on which token you mean?

If you are talking about the token that is listed in the example for the configuration.yaml:
```
notify:
  - platform: wapi
    name: wapi whatsapp notifire
    session: ABCD #Set your own session
    url: http://192.168.0.238:3000/client/sendMessage #Set the url configured in the whatsapp-api docker
    token: #Optional - This token shoukd be equel to the token you set in the whatsapp-api configuration.
```

you dont need it necessarry. Its just an additional option to protect potentially other people of calling this.
As it is written in the README file:
You can set whatever token you like, but it has to be the same as it is set on the whatsapp api server side.
